export default async function handler(req, res) {
  const { proposalId, severity, event, evidence, yes, no, timestamp, txHash } = req.query

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cerberus Incident Report</title>
  <style>
    body { background: #0a0a0a; color: #e0e0e0; font-family: monospace; padding: 2rem; max-width: 800px; margin: 0 auto; }
    h1 { color: #ff4400; font-size: 1.5rem; }
    .badge { display: inline-block; padding: 0.3rem 0.8rem; border-radius: 4px; font-size: 0.8rem; font-weight: 700; }
    .critical { background: #ff330022; color: #ff3300; border: 1px solid #ff3300; }
    .high { background: #ff660022; color: #ff6600; border: 1px solid #ff6600; }
    .executed { background: #00ff8822; color: #00ff88; border: 1px solid #00ff88; }
    .section { background: #111; border: 1px solid #1a1a1a; border-radius: 4px; padding: 1rem; margin: 1rem 0; }
    .label { font-size: 0.65rem; color: #444; letter-spacing: 0.2em; margin-bottom: 0.5rem; }
    .value { font-size: 0.9rem; color: #ccc; }
    .agent { display: flex; gap: 1rem; padding: 0.5rem 0; border-bottom: 1px solid #1a1a1a; }
    a { color: #00aaff; }
    .footer { text-align: center; color: #333; font-size: 0.7rem; margin-top: 2rem; }
  </style>
</head>
<body>
  <h1>🐺 CERBERUS INCIDENT REPORT</h1>
  <p style="color:#555; font-size:0.8rem;">Generated by Cerberus Protocol · ETHGlobal Open Agents 2026</p>

  <div style="display:flex; gap:0.5rem; margin:1rem 0; flex-wrap:wrap;">
    <span class="badge ${severity === 'CRITICAL' ? 'critical' : 'high'}">${severity || 'CRITICAL'}</span>
    <span class="badge executed">✅ EXECUTED</span>
    <span class="badge" style="background:#00aaff22; color:#00aaff; border:1px solid #00aaff">${event || 'SuspiciousActivity'}</span>
  </div>

  <div class="section">
    <div class="label">INCIDENT DETAILS</div>
    <div class="agent"><span style="color:#444;min-width:120px">Proposal ID</span><span class="value">${proposalId || 'N/A'}</span></div>
    <div class="agent"><span style="color:#444;min-width:120px">Event Type</span><span class="value">${event || 'SuspiciousActivity'}</span></div>
    <div class="agent"><span style="color:#444;min-width:120px">Severity</span><span class="value" style="color:${severity === 'CRITICAL' ? '#ff3300' : '#ff6600'}">${severity || 'CRITICAL'}</span></div>
    <div class="agent"><span style="color:#444;min-width:120px">Evidence</span><span class="value">${evidence || 'Suspicious activity detected'}</span></div>
    <div class="agent"><span style="color:#444;min-width:120px">Timestamp</span><span class="value">${timestamp || new Date().toISOString()}</span></div>
    ${txHash ? `<div class="agent"><span style="color:#444;min-width:120px">TX Hash</span><a href="https://sepolia.etherscan.io/tx/${txHash}" target="_blank">${txHash.slice(0,20)}... ↗</a></div>` : ''}
  </div>

  <div class="section">
    <div class="label">AI SWARM CONSENSUS</div>
    <div class="agent">
      <span>👁</span>
      <div>
        <div style="color:#ff6600;font-size:0.8rem">watcher.cerberusprotocol.eth</div>
        <div style="color:#555;font-size:0.7rem">DETECTED — Threat proposed to swarm</div>
      </div>
    </div>
    <div class="agent">
      <span>⚖️</span>
      <div>
        <div style="color:#00ff88;font-size:0.8rem">validatora.watcher.cerberusprotocol.eth</div>
        <div style="color:#555;font-size:0.7rem">YES — Independent vote cast</div>
      </div>
    </div>
    <div class="agent">
      <span>🛡️</span>
      <div>
        <div style="color:#00ff88;font-size:0.8rem">validatorb.validatora.watcher.cerberusprotocol.eth</div>
        <div style="color:#555;font-size:0.7rem">YES — Independent vote cast</div>
      </div>
    </div>
    <div style="margin-top:0.75rem;padding:0.5rem;background:#00ff8811;border-radius:4px;font-size:0.8rem;color:#00ff88;font-weight:700">
      ✅ CONSENSUS: ${yes || 2}/3 YES — EXECUTED
    </div>
  </div>

  <div class="section">
    <div class="label">ACTIONS TAKEN</div>
    <div class="agent"><span>⚡</span><span>KeeperHub called emergencyPause() on CerberusVault</span></div>
    <div class="agent"><span>🗄️</span><span>0G Galileo audit log written — immutable record</span></div>
    <div class="agent"><span>📱</span><span>Telegram alert sent to security team</span></div>
    <div class="agent"><span>🔵</span><span>All agents verified via ENS — cerberusprotocol.eth</span></div>
  </div>

  <div class="section">
    <div class="label">VERIFY ON-CHAIN</div>
    <div class="agent"><span style="color:#444;min-width:120px">CerberusVault</span>
      <a href="https://sepolia.etherscan.io/address/0x6eb6fde2d2462b0afa9f169372677fd69955bad8" target="_blank">0x6eb6fde2... ↗</a>
    </div>
    <div class="agent"><span style="color:#444;min-width:120px">ENS Profile</span>
      <a href="https://sepolia.app.ens.domains/cerberusprotocol.eth" target="_blank">cerberusprotocol.eth ↗</a>
    </div>
    <div class="agent"><span style="color:#444;min-width:120px">System Status</span>
      <a href="https://cerberus-protocol.vercel.app/api/status" target="_blank">/api/status ↗</a>
    </div>
  </div>

  <div class="footer">
    Cerberus Protocol · ETHGlobal Open Agents 2026 · cerberus-protocol.vercel.app<br>
    Three-headed AI security swarm · No central coordinator · Real on-chain execution
  </div>
</body>
</html>`

  res.setHeader('Content-Type', 'text/html')
  return res.status(200).send(html)
}
